name: Create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release, in format 1.2.3'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:

      - name: Check version format
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            text="Version ${{ github.event.inputs.version }} is not valid."
            echo "::error::$text"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Update version in pyproject.toml
        run: poetry version ${{ github.event.inputs.version }}

      - name: Commit and push pyproject.toml
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit_and_push
        with:
          branch: main
          commit_message: "Bump version ${{ github.event.inputs.version }}"

      - name: Publish project in pypi.org
        run: poetry publish --no-interaction --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Release version
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: dist/*
