name: Create new release

on:
  push:
    branches:
      - main

jobs:
  check_new_version_and_release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Get version
        id: version
        run:
          V=$(poetry version -s)
          echo '::set-output name=VERSION::${V}'

      # https://github.com/mukunku/tag-exists-action
      - uses: mukunku/tag-exists-action@v1.0.0
        id: check_tag
        with:
          tag: ${{ steps.version.outputs.VERSION }}

      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit and push pyproject.toml
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: ${{ github.event.inputs.version }}
          commit_message: "Bump version ${{ github.event.inputs.version }}"

      - name: Publish project in pypi.org
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        run: poetry publish --no-interaction --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      # https://github.com/softprops/action-gh-release
      - name: Release version
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: dist/*
